# Individual inference methods for InternLM X-Composer 2.5 7B
from typing import Dict
import torch
from torchvision import transforms
from PIL import Image
from io import BytesIO
import requests
import os
import numpy as np
from transformers import AutoModel, AutoTokenizer



class InternVLM():
    def __init__(self):
        pass

    def prepare_inputs(self, messages: list[Dict], **kwargs):
        """
        Returns a separate history, the prompt and a list of images to be passed to the model

        :param messages: A list[Dict] type object passed to the backend containing 'role', 'content' and 'image'
        :return history, prompt, image: Inputs to the model
        """
        history = []
        image = []
        image_counter = 0
        prev_user_msg = ""

        for m in messages:
            if m['role'] == 'user':
                prev_user_msg = m['content']
                if 'image' in m:
                    if isinstance(m['image'], str):
                        # A single image is passed
                        image_counter += 1
                        prev_user_msg = f"Image{image_counter} <ImageHere>; " + prev_user_msg
                        image.append(m['image'])
                    elif isinstance(m['image'], list):
                        # A list of images is passed
                        for img in m['image']:
                            image_counter += 1
                            prev_user_msg = f"Image{image_counter} <ImageHere>; " + prev_user_msg
                            image.append(img)
                    else:
                        print("Please pass a valid type of image in the message - Either a str or List[str]")

            elif m['role'] == 'assistant':
                # Append User+Assistant Message in Sequence
                history.append((prev_user_msg, m['content']))

        return {
            "prompt": prev_user_msg,
            "image": image,
            "kwargs": {"history": history}
        }

    def get_tokens(self, prompt: str, processor: AutoTokenizer, **kwargs):
        """
        Get the tokens passed to the model for context check

        :param prompt: The current prompt passed to the model
        :param processor: The processor used for the model
        :param kwargs: The kwargs passed to the model [history,...]

        :return: The tokens passed to the model
        """

        history = kwargs["history"]

        collect_history = ""
        for h in history:
            collect_history += h[0] + h[1]
        prompt_text = prompt + collect_history
        prompt_tokens = processor.tokenize(prompt_text)

        return prompt_tokens

    # def download_images(self, images: list) -> list:
    #     """
    #     Download images from URLs and save them locally.
    #
    #     :param images: List of image URLs or local paths.
    #     :return: List of local paths to the downloaded images.
    #     """
    #     local_paths = []
    #     for idx, image in enumerate(images):
    #         if image.startswith('http://') or image.startswith('https://'):
    #             local_path = f'temp_image_{idx}.jpg'
    #             response = requests.get(image)
    #             if response.status_code == 200:
    #                 image = Image.open(BytesIO(response.content))
    #
    #         else:
    #             image = Image.open(image)
    #             local_path = f'temp_image_{idx}.jpg'
    #
    #         if image.mode == 'RGBA':
    #             fill = (255, 255, 255, 255)
    #         else:
    #             fill = (255, 255, 255)
    #
    #         image = transforms.functional.pad(image, padding=[0, 0, 0, 0], fill=fill)
    #
    #         image.save(local_path)
    #
    #         local_paths.append(local_path)
    #
    #     return local_paths

    def cleanup_images(self, images: list):
        """
        Delete downloaded images from local storage.

        :param images: List of local image paths.
        """
        for image in images:
            if image.startswith('temp_image_'):
                os.remove(image)

    def generate_output(self, prompt: str, image: list, model: AutoModel,
                        processor: AutoTokenizer, **kwargs) -> [Dict, str]:
        """
        Generate Outputs [response, response_text] for InternLM type Models
        Ref - https://huggingface.co/internlm/internlm-xcomposer2d5-7b

        :param prompt: The text prompt to be used for generating the response.
        :param image: A list of images to be included in the model's input.
        :param model: The model used for generating the output. This should be compatible with InternLM type models.
        :param processor: The processor/tokenizer used to preprocess the prompt.
        :param **kwargs: Additional keyword arguments that may be required by the model or tokenizer.

        :return response: The raw output from the model.
        :return response_text: The decoded text response generated by the model.
        """

        # TODO - Raise Warning When Using CPU and not CUDA
        # TODO - Add model.chat args in model registry, pass them as additional kwargs

        # Download the image temporarily if a local path is not given, then delete it
        # image = self.download_images(image)

        image = [Image.open(img) for img in image]
        image = [np.array(img) for img in image]
        image = [torch.tensor(img) for img in image]
        history = kwargs["history"]

        # By default unset Gradient Calculation for inferencing
        torch.set_grad_enabled(False)

        model = model.cuda().eval()
        model.tokenizer = processor

        # Use CUDA to get the response
        with torch.autocast(device_type='cuda', dtype=torch.float16):
            # Process each image and handle channel mismatch
            # processed_images = []
            # for image_path in image:
            #     img = Image.open(image_path)
            #     if img.mode == 'RGBA':
            #         fill = (255, 255, 255, 255)
            #     else:
            #         fill = (255, 255, 255)
            #
            #     img = transforms.functional.pad(img, padding=[0,0,0,0], fill=fill)
            #     processed_images.append(img)

            gen_text, _ = model.chat(processor, prompt, image,
                                     do_sample=False,
                                     num_beams=3,
                                     top_p=1,
                                     history=history,
                                     use_meta=True)

            # Unset top_p manually to avoid the following warning
            # UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.

            response_text = gen_text.strip()

            # Cast into Clemgame compatible form
            response = {"response": gen_text}

        # Delete the image if it was downloaded
        self.cleanup_images(image)

        return response, response_text
